# linear_regression_sklearn/Dockerfile
FROM python:3.9-slim
WORKDIR /app
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir jupyterlab gradio numpy joblib scikit-learn matplotlib
EXPOSE 8888 # Jupyter Lab
EXPOSE 7861 # Gradio 應用
CMD ["tail", "-f", "/dev/null"]
